Samesystem/CommentFormat:
  Description: 'Samesystem comment format cop.'
  Enabled: true
  VersionAdded: '0.82'

Samesystem/NamingMatters:
  Description: 'Samesystem cop that catches some bad variable naming (i.e. "it").'
  Enabled: true
  EnforcedStyle: naming_matters
  SupportedStyles: ['naming_matters']
  VersionAdded: '1.0.0'
